{
  buildPkgs,
  crossPkgs,
  externalMappings ? [],
  glibcPlugins ? [],
  toolchainConfig ? {},
}: let
  lib = buildPkgs.lib;
  rustScript = import ../builder/rustScript.nix {inherit buildPkgs;};

  # Determine where glibc looks for libraries and config at runtime.
  glibcRuntimePrefix = (toolchainConfig.glibc or {}).runtimePrefix or null;
  glibcEtcDir =
    if glibcRuntimePrefix != null then "/etc"
    else "etc";
  pluginLibDir =
    if glibcRuntimePrefix != null then "${glibcRuntimePrefix}/lib"
    else "lib";

  # --- glibc plugin / nsswitch.conf generation ---
  pluginDecls = map (p:
    if p ? passthru.glibcPlugin then p.passthru.glibcPlugin
    else throw "glibcPlugin: ${p.name or "<unknown>"} is missing passthru.glibcPlugin"
  ) glibcPlugins;

  # Merge nssDatabases from all plugins: concatenate module lists per database.
  mergedNssDatabases = lib.foldl' (acc: decl:
    acc // (lib.mapAttrs' (db: modules:
      lib.nameValuePair db ((acc.${db} or []) ++ modules)
    ) (decl.nssDatabases or {}))
  ) {} pluginDecls;

  nssDatabaseLines = lib.concatStringsSep "\n" (lib.mapAttrsToList (db: modules:
    "${db}: ${lib.concatStringsSep " " modules}"
  ) mergedNssDatabases);

  nssExtraLines = lib.concatStringsSep "\n" (
    lib.concatMap (decl:
      lib.filter (line: line != "") (lib.splitString "\n" (decl.nssExtraLines or ""))
    ) pluginDecls
  );

  nsswitchConfText = lib.concatStringsSep "\n" (
    ["# Generated by ardos-packer2 — do not edit manually."]
    ++ lib.optional (nssDatabaseLines != "") nssDatabaseLines
    ++ lib.optional (nssExtraLines != "") nssExtraLines
    ++ [""]
  );

  nsswitchConf = buildPkgs.writeText "nsswitch.conf" nsswitchConfText;

  hasGlibcPlugins = glibcPlugins != [];

  # Compile the sysroot population tool from Rust.
  populateSysroot = rustScript "populate-sysroot" ./populate-sysroot.rs;

  # Generate external mappings file from { drv, runtimeLayout } entries.
  mappingScriptToLayout = mapping: ''
    echo "# ardos-external-mapping ${mapping.drv}" >> "$out"
    ${lib.concatMapStrings (entry: ''
      printf '%s -> %s\n' "${entry.source}" "${entry.target}" >> "$out"
    '') mapping.runtimeLayout}
  '';

  externalMappingsFile =
    if externalMappings == []
    then "-"
    else
      buildPkgs.runCommand "ardos-external-runtime-mappings" {
        nativeBuildInputs = [buildPkgs.coreutils buildPkgs.bash];
      } ''
        : > "$out"
        ${lib.concatMapStringsSep "\n" mappingScriptToLayout externalMappings}
      '';
in {
  mkSysroot = {
    includePackages,
    name ? "ardos-sysroot",
  }: let
    closure = buildPkgs.closureInfo {rootPaths = includePackages;};
  in
    buildPkgs.runCommand name {
      nativeBuildInputs = [buildPkgs.coreutils populateSysroot];
    } ''
      work="$PWD/sysroot"
      mkdir -p "$work"

      populate-sysroot ${closure} ${externalMappingsFile} "$work"

      ${lib.optionalString hasGlibcPlugins ''
        if grep -Fxq "${crossPkgs.glibc}" ${closure}/store-paths; then
          ${lib.concatMapStringsSep "\n" (plugin: ''
            if [ -d "${plugin}/lib" ]; then
              mkdir -p "$work/${pluginLibDir}"
              cp -R --no-preserve=mode "${plugin}/lib"/. "$work/${pluginLibDir}"/
            fi
          '') glibcPlugins}


          mkdir -p "$work/${glibcEtcDir}"
          cp ${nsswitchConf} "$work/${glibcEtcDir}/nsswitch.conf"
        fi
      ''}

      cp -a "$work"/. "$out"/
    '';
}
