{
  buildPkgs,
  crossPkgs,
  externalMappings ? [],
  glibcPlugins ? [],
  toolchainConfig ? {},
}: let
  lib = buildPkgs.lib;

  # Determine where glibc looks for libraries and config at runtime.
  glibcRuntimePrefix = (toolchainConfig.glibc or {}).runtimePrefix or null;
  glibcEtcDir =
    if glibcRuntimePrefix != null then "/etc"
    else "etc";
  pluginLibDir =
    if glibcRuntimePrefix != null then "${glibcRuntimePrefix}/lib"
    else "lib";

  # --- glibc plugin / nsswitch.conf generation ---
  pluginDecls = map (p:
    if p ? passthru.glibcPlugin then p.passthru.glibcPlugin
    else throw "glibcPlugin: ${p.name or "<unknown>"} is missing passthru.glibcPlugin"
  ) glibcPlugins;

  # Merge nssDatabases from all plugins: concatenate module lists per database.
  mergedNssDatabases = lib.foldl' (acc: decl:
    acc // (lib.mapAttrs' (db: modules:
      lib.nameValuePair db ((acc.${db} or []) ++ modules)
    ) (decl.nssDatabases or {}))
  ) {} pluginDecls;

  nssDatabaseLines = lib.concatStringsSep "\n" (lib.mapAttrsToList (db: modules:
    "${db}: ${lib.concatStringsSep " " modules}"
  ) mergedNssDatabases);

  nssExtraLines = lib.concatStringsSep "\n" (
    lib.concatMap (decl:
      lib.filter (line: line != "") (lib.splitString "\n" (decl.nssExtraLines or ""))
    ) pluginDecls
  );

  nsswitchConfText = lib.concatStringsSep "\n" (
    ["# Generated by ardos-packer2 — do not edit manually."]
    ++ lib.optional (nssDatabaseLines != "") nssDatabaseLines
    ++ lib.optional (nssExtraLines != "") nssExtraLines
    ++ [""]
  );

  nsswitchConf = buildPkgs.writeText "nsswitch.conf" nsswitchConfText;

  hasGlibcPlugins = glibcPlugins != [];

  # Generate external mappings file from { drv, runtimeLayout } entries.
  # Each entry's runtimeLayout is written as ardos-layout lines prefixed by a
  # section header so populate-map.rs can apply them per-dependency.
  mappingScriptToLayout = mapping: ''
    echo "# ardos-external-mapping ${mapping.drv}" >> "$out"
    ${lib.concatMapStrings (entry: ''
      printf '%s -> %s\n' "${entry.source}" "${entry.target}" >> "$out"
    '') mapping.runtimeLayout}
  '';

  externalMappingsFile =
    if externalMappings == []
    then null
    else
      buildPkgs.runCommand "ardos-external-runtime-mappings" {
        nativeBuildInputs = [buildPkgs.coreutils buildPkgs.bash];
      } ''
        : > "$out"
        ${lib.concatMapStringsSep "\n" mappingScriptToLayout externalMappings}
      '';
in {
  mkSysroot = {
    includePackages,
    name ? "ardos-sysroot",
  }: let
    closure = buildPkgs.closureInfo {rootPaths = includePackages;};
  in
    buildPkgs.runCommand name {
      nativeBuildInputs = [
        buildPkgs.coreutils
        buildPkgs.findutils
      ];
    } ''
      mkdir -p "$out"

      copy_mapping() {
        src_path="$1"
        dest_path="$2"

        if [ ! -e "$src_path" ] && [ ! -L "$src_path" ]; then
          # Folder mappings may reference non-existent dirs (e.g. lib/ when only
          # bin/ is installed).  Skip silently for folder mappings; error on
          # individual files.
          case "$src_path" in
            */)
              echo "warning: folder mapping source does not exist, skipping: $src_path -> ''${dest_path#$out}" >&2
              return 0
              ;;
            *)
              echo "error: broken Ardos runtime mapping: $src_path -> ''${dest_path#$out}" >&2
              exit 1
              ;;
          esac
        fi

        mkdir -p "$(dirname "$dest_path")"

        # Folder mappings (trailing / on source) expand by copying contents.
        # We must NOT use `cp -a` on directories — it preserves source mode
        # (often 555) which seals the directory read-only in the Nix sandbox.
        # Regular files are copied without preserving mode, then executables
        # get chmod +x so the dynamic linker and other binaries work in proot.
        # Symlinks are always copied with -a.
        # Folder mappings merge into existing directories (last-wins per file)
        # rather than replacing the whole directory.
        case "$src_path" in
          */)
            while IFS= read -r -d $'\0' item; do
              rel="''${item#$src_path}"
              dest="$dest_path$rel"
              if [ -d "$item" ] && [ ! -L "$item" ]; then
                mkdir -p "$dest"
              elif [ -L "$item" ]; then
                mkdir -p "$(dirname "$dest")"
                rm -f "$dest"
                cp -a --no-preserve=ownership "$item" "$dest"
              else
                mkdir -p "$(dirname "$dest")"
                rm -f "$dest"
                cp --no-preserve=mode "$item" "$dest"
                [ -x "$item" ] && chmod +x "$dest" || true
              fi
            done < <(find "$src_path" -mindepth 1 -print0)
            ;;
          *)
            # Last-wins for individual files: remove destination first.
            if [ -e "$dest_path" ] || [ -L "$dest_path" ]; then
              rm -rf "$dest_path"
            fi
            cp -a --no-preserve=ownership "$src_path" "$dest_path"
            ;;
        esac
      }

      apply_layout() {
        store_path="$1"
        layout="$2"

        while IFS= read -r line || [ -n "$line" ]; do
          case "$line" in ""|\#*) continue ;; esac

          src_rel="''${line%% -> *}"
          dest_abs="''${line#* -> }"

          # Special target /dev/null means "exclude from ROM".  This lets
          # packages override a recursive folder mapping by excluding specific
          # files (e.g. lib/sensitive.so -> /dev/null).
          case "$dest_abs" in
            /dev/null) continue ;;
          esac

          case "$src_rel" in
            /*) src_path="$src_rel" ;;
            *) src_path="$store_path/$src_rel" ;;
          esac
          dest_path="$out/''${dest_abs#/}"

          # Skip GNU ld scripts — they are linker inputs only and must
          # never be materialized into the runtime ROM.
          if [ -f "$src_path" ] && [ ! -L "$src_path" ]; then
            case "$(head -c 4096 "$src_path" 2>/dev/null)" in
              "/* GNU ld script"*) continue ;;
            esac
          fi

          copy_mapping "$src_path" "$dest_path"
        done < "$layout"
      }

      while IFS= read -r store_path; do
        layout="$store_path/nix-support/ardos-layout"
        [ -f "$layout" ] || continue
        apply_layout "$store_path" "$layout"
      done < ${closure}/store-paths

      ${lib.optionalString (externalMappingsFile != null) ''
        active_base=""
        active_applies=0
        while IFS= read -r line || [ -n "$line" ]; do
          case "$line" in
            "# ardos-external-mapping "*)
              active_base="''${line#\# ardos-external-mapping }"
              if grep -Fxq "$active_base" ${closure}/store-paths; then
                active_applies=1
              else
                active_applies=0
              fi
              continue
              ;;
          esac

          [ "$active_applies" = 1 ] || continue
          [ -n "$active_base" ] || continue
          case "$line" in ""|\#*) continue ;; esac

          tmp_layout=$(mktemp)
          printf '%s\n' "$line" > "$tmp_layout"
          apply_layout "$active_base" "$tmp_layout"
          rm -f "$tmp_layout"
        done < ${externalMappingsFile}
      ''}

      # --- glibc plugin assembly ---
      # Only apply glibc plugins if glibc itself is in the sysroot closure.
      ${lib.optionalString hasGlibcPlugins ''
        if grep -Fxq "${crossPkgs.glibc}" ${closure}/store-paths; then
          ${lib.concatMapStringsSep "\n" (plugin: ''
            if [ -d "${plugin}/lib" ]; then
              mkdir -p "$out/${pluginLibDir}"
              cp -R --no-preserve=mode "${plugin}/lib"/. "$out/${pluginLibDir}"/
            fi
          '') glibcPlugins}


          mkdir -p "$out/${glibcEtcDir}"
          cp ${nsswitchConf} "$out/${glibcEtcDir}/nsswitch.conf"
        fi
      ''}
    '';
}
